export const env = {
	API_KEY: process.env.NEXT_PUBLIC_API_KEY,
	AUTH_DOMAIN: process.env.AUTH_DOMAIN,
	PROJECT_ID: process.env.PROJECT_ID,
	STORAGE_BUCKET: process.env.NEXT_PUBLIC_STORAGE_BUCKET,
	MESSAGING_SENDER_ID: process.env.MESSAGING_SENDER_ID,
	APP_ID: process.env.APP_ID,
	EMAIL_USER: process.env.EMAIL_USER,
	EMAIL_PASSWORD: process.env.EMAIL_PASSWORD,
};
