export const env = {
	API_KEY: process.env.NEXT_PUBLIC_API_KEY,
	AUTH_DOMAIN: process.env.NEXT_PUBLIC_AUTH_DOMAIN,
	PROJECT_ID: process.env.NEXT_PUBLIC_PROJECT_ID,
	STORAGE_BUCKET: process.env.NEXT_PUBLIC_STORAGE_BUCKET,
	MESSAGING_SENDER_ID: process.env.NEXT_PUBLIC_MESSAGING_SENDER_ID,
	APP_ID: process.env.NEXT_PUBLIC_APP_ID,
	GOOGLE_MAPS_API_KEY: process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY,
	MAP_ID: process.env.NEXT_PUBLIC_MAP_ID,
	EMAIL_USER: process.env.EMAIL_USER,
	EMAIL_PASSWORD: process.env.EMAIL_PASSWORD,
	EMAIL_TO: process.env.EMAIL_TO,
};
